name: Check image alt text

on:
  pull_request:
    paths:
      - 'content/en/**/*.md'
      - 'hack/verify-alt-text.py'
      - 'Makefile'

jobs:
  alt-text:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Validate alt text on images
      run: make verify-alt-text
